#!/bin/bash -e

ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/sdnotify-proxy"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

eval $(go env)

if [ ${GOOS} = "linux" ]; then
	echo "Building sdnotify-proxy..."
	go build -o ${GOBIN}/sdnotify-proxy ${REPO_PATH}
else
	echo "Not on Linux - skipping sdnotify-proxy build"
fi
